name: Hämta Luncher

on:
  schedule:
    # Körs klockan 06:00 UTC varje dag (vilket är 07:00 eller 08:00 i Sverige)
    - cron: '0 6 * * *'
  # Gör att du kan starta den manuellt med en knapp (bra för test)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hämta din kod
        uses: actions/checkout@v4

      - name: Installera Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installera verktyg
        run: pip install requests beautifulsoup4

      - name: Kör roboten
        run: python scraper.py

      - name: Spara den nya menyn
        run: |
          git config --global user.name "Lunch-Robot"
          git config --global user.email "robot@lunchkollen.se"
          # Kolla om filen har ändrats
          if [[ -n $(git status -s lunch_data.json) ]]; then
            git add lunch_data.json
            git commit -m "Uppdaterade lunchen"
            git push
          else
            echo "Ingen förändring i menyn idag."
          fi
